### ISSUE TITLE
Distances calculated with bike_distmat() seem incorrect

### ISSUE THREAD

**Issue by JorisKlingen** [ropensci/bikedata#52]
The distances between the stations using bike_distmat() seem off for a large part of the station pairs. For instance, with the code below I calculate the distance for the London stations and add a column with euclidean distance (using raster package). The resulting plot shows that for a lot of cases the euclidean distance exceeds the distance calculated using bike_distmat, which cannot be correct. Also doing some manual tests on google maps shows that some distances are simply too short.

Thank you in advance.

` library(bikedata)
  library(data.table)
  library(raster)
 
  #set up the bikedb
  data_dir <- paste0(getwd(), "/data/Rbikedata")
  bikedb <- file.path (data_dir,'testdb')
  dl_bikedata (city ='London', data_dir=data_dir, dates = 201701:201702)
  store_bikedata (data_dir = data_dir, bikedb = bikedb)
 
  #load stations data
  dtSs <- data.table(bike_stations(bikedb = bikedb))
 
  #load distance matrix
  dtDs <- data.table(bike_distmat(bikedb=bikedb, city="London", expand = 0, long = T, quiet = F))
 
  #join distance matrix with start_station data                  
  setkey(dtSs, "stn_id")
  setkey(dtDs, "start_station_id")
  dtDs <- dtDs[dtSs[, .(stn_id, name, latitude, longitude)]]
  setnames(dtDs, c("name","longitude","latitude") , c("start_station_name","lon_start","lat_start") )
 
  #join distance matrix with end_station data         
  setkey(dtDs, "end_station_id")
  dtDs <- dtDs[dtSs[, .(stn_id, name, latitude, longitude)]]
  setnames(dtDs, c("name","longitude","latitude") , c("end_station_name","lon_end","lat_end") )

  #calculate euclidean distance using raster package
  dtDs[, Dist_eucl:=pointDistance(dtDs[,.(lon=lon_start,lat=lat_start)], dtDs[,.(lon=lon_end,lat=lat_end)], lonlat = T)]
 
  #select a subset for faster plotting
  vSubset <- 1:(.05*nrow(dtDs))
 
  #plot the euclidean against the over the network distance
  plot(dtDs[vSubset, Dist_eucl], dtDs[vSubset, distance])`

![bikedata_plot](https://user-images.githubusercontent.com/34268395/33601566-ea833600-d9ac-11e7-8958-26f4e04fb6e0.png)

**Comment by mpadge** [comment]
Thanks @JorisKlingen! This was a very important bug that you found, caused by an overseen mismatch between 0-based C++ indices and 1-based R indices in the [`dodgr`](https://github.com/ATFutures/dodgr) package used to calculate these distances. With [this commit](https://github.com/ATFutures/dodgr/commit/68a8fc8fbfdeab71485f09319a8bbd86783e790d), your example now yields only 139 from > 500,000 station pairs for which great circle distances are greater than street network shortest paths. These arise in situations where the station coordinates map onto parts of the street network that are closer together in network terms than the great circle line between the station pair itself. They are only for station pairs that are very close together, and are appropriate in these cases, reflecting as they do slight mismatches between given station locations and the underlying OSM street network, and for which the distance mis-matches are very, very small.
